@startuml Design_Class_Diagram

class Account {
    -balance: double
    +deposit(amount: double): void
    +withdraw(amount: double): void
}

class RaffleCup {
    -dice: Die[]
    +roll(): int[]
}

class Die {
    -numberOfSides: int
    +roll(): int[]
}

class Bank {
    -balance: double
    +takeMoney(account: Account): void
    +giveMoney(account: Account): void
}

class Player {
    -account: Account
    -name: String
    -age: int
}

class Board {
    -tokens: Token[]
    -fields: Field[]

    +nextTurn(): void
}

abstract class Field {
    -tokens: Tokens[]
    -name: String
    -position: int
    -fieldType: FieldType
    +{abstract} landOnField(token: Token): void
}

abstract class PassableField {
    +{abstract} passField(token: Token): void
}

class GoField {
    +landOnField(token: Token): void
    +landOnField(token: Token): void
}

class PropertyField {
    -price: double
    -owner: Player

    +landOnField(token: Token): void
}

class Token {
    -tokenType: TokenType
    -player: Player
}

enum FieldType {
    PROPERTY,
    CHANCE,
    START,
    JAIL,
    PARKING,
    GO_TO_JAIL,
}

enum TokenType {
    DOG,
    CAT,
    CAR,
    BOAT,
}

Field <|-- PassableField
Field <|-- PropertyField 
PassableField <|-- GoField
Board "1      " *-- "1..* " Field
Board "1 " *-- "2    " Token
Field "1 " --> "1" FieldType
Token "1 " *-- "1" Player
Token "1 " o-- "1    " TokenType



@enduml