@startuml Domain_Model

left to right direction

object Account
object RaffleCup
object Die
object Bank
object Player
object Field
object Board
object Token
object Property

Player"1"--"1"Token: "is associated with"
Player"1"--"1"Account: "has"
Player"1" -- "1"RaffleCup: "rolls with"
RaffleCup"1"-- "1"Die: "contains"
Board "1"--"26" Field: "has"
Token "2..4"--"1" Board: "moves on"
Token"0..4" -- "1"Field: "lands on"
Account"1"--"1" Bank: "exchange money with"
Token"1" -- "1"RaffleCup: "moves according to"

@enduml