@startuml Domain_Model

left to right direction

object Account
object RaffleCup
object Die
object Bank
object Player
object Jail
object Field
object ChanceCard
object Board
object Property
object Token

Player"1"--"1"Token: "is associated with"
Player"1"--"1"Account: "has"
Player"1" -- "1"RaffleCup: "rolls with"
RaffleCup"1"-- "1"Die: "contains"
Board "1"--"26" Field: "has"
Token "2..4"--"1" Board: "moves on"
Token"0..4" -- "1"Field: "lands on"
Account"1"--"1" Bank: "exchange money with"
Token"1"--"0..16" Property: "owns"
Property"1" -- "1"Field: "is associated with"
Board "1"--"20" ChanceCard: "has"
Player"1" -- "1"ChanceCard: "picks up"
Jail"1" -- "1"Field: "is associated with"
Token"0..4" -- "1"Jail: "is in"
Token"1" -- "1"RaffleCup: "moves according to"
Bank"1" -- "1"Property: "is paid value"

@enduml