@startuml UseCaseDiagram

left to right direction

actor Player

package Game {
    usecase "Make Transaction" as UC1
    usecase "End game" as UC2
    usecase "Start game" as UC3
    usecase "Lose game" as UC4
    usecase "Win game" as UC5
    usecase UC6 as "Use Turn
    --"
}

Player -- UC6
Player -- UC3
UC6 <-[dashed]- UC1: <<extend>>
UC3 <-[dashed]- UC1: <<include>>
@enduml